aws_region            = "us-east-1"
env                   = "dev"
cluster_name          = "dev-eks-cluster"
vpc_cidr_block        = "10.0.0.0/16"
public_subnet_cidrs   = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs  = ["10.0.3.0/24", "10.0.4.0/24"]
availability_zones    = ["us-east-1a", "us-east-1b"]
eks_version           = "1.29"
desired_capacity      = 2
min_size              = 1
max_size              = 3
instance_types        = ["t3.medium"]
